version: '3.8'

services:
  nfl-qb-dashboard:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped 